### ISSUE TITLE
package-buffer-info: Package lacks a "Version" or "Package-Version" header

### ISSUE THREAD

**Issue by marcomansilla** [legoscia/bic#1]
I'm running Emacs 25.1 on Debian, following the instructions.

- Cloned the repo inside .emacs.d/vendor/bic
- M-x package-install-file ~/.emacs.d/vendor/bic/bic.el
- complains about not finding bic-core.el
- when try to compile the file it returns that package lacks version or package version.

**Comment by marcomansilla** [comment]
fixed by adding same version in bic.el

**Comment by marcomansilla** [comment]
Same thing happens with other files, lack of version.

**Comment by legoscia** [comment]
You need to run `package-install-file` on the directory, not the `bic.el` file, i.e. `~/.emacs.d/vendor/bic/`. That way, it should pick up all the files.
