### ISSUE TITLE
Nearly there

### ISSUE THREAD

**Issue by jwintz** [legoscia/bic#2]
Hi,

I've been trying `bic` since to me it provides unique features such as *not* relying on external tools nor polluting the file system with maildirs.

However, I could not get mail once some accounts setup.

`*Message*` and `bic` buffers do not provide significant information.

How can I dig a little bit more ?

**Comment by legoscia** [comment]
The `*fsm-debug*` buffer should tell you where it gets stuck. Perhaps it's an IMAP server that I haven't tested against behaving a little bit differently, confusing the client...

**Comment by jwintz** [comment]
Oh it finally works awesomely well.
